project:
  type: website
  output-dir: docs

brand: _brand.yml

website:
  title: "Matt Barger"
  navbar:
    right:
      - text: "Posts"
        file: posts.qmd
      - text: "Now"
        file: now2024-01-29.qmd
      - text: '{{< fa brands github >}}'
        href: https://github.com/mattbarger
      - text: '{{< fa brands bluesky >}}'
        href: https://bsky.app/profile/mattbarger.bsky.social


format:
  html:
    theme: 
      dark: darkly
      light: flatly
    typography:
      base: Inter
      headings: Inter
      monospace: Fira Mono

editor: visual

