project:
  type: website
  output-dir: docs


website:
  title: "Matt Barger"
  navbar:
    right:
      - text: "Posts"
        file: posts.qmd
      - text: "Now"
        file: now2024-01-29.qmd
      - text: '{{< fa brands github >}}'
        href: https://github.com/mattbarger
      - text: '{{< fa brands bluesky >}}'
        href: https://bsky.app/profile/mattbarger.bsky.social


format:
  html:
    theme: 
      dark:
        - darkly
        - styles.scss
      light:
        - flatly
        - styles.scss
    include-in-header: fonts.html
    

editor: visual

